const tags = [
    'Breakfast',
    'Lunch',
    'Dinner',
    'Dessert',
    'Snack',
    'American',
    'Mexican',
    'Italian',
    'Thai',
    'Indian',
    'Chinese',
    'Seafood',
    'Chicken',
    'Beef',
    'Pork',
    'Vegetables',
    'Fruit',
    'Sweet',
    'Spicy',
    'Savory',
    'Other',
  ]
module.exports = tags